import type { HeaderRule } from '../types';

/**
 * Escapes a string for safe embedding inside a bash single-quoted argument.
 *
 * Single quotes cannot appear inside a single-quoted string; the canonical
 * workaround is to close the string, emit a literal single quote, and reopen:
 *   it'\''s → evaluates to: it's
 */
function shEscape(s: string): string {
  return s.replace(/'/g, "'\\''");
}

/**
 * Produces a bash-safe `curl` command that replays the given URL with the
 * supplied cookies and/or enabled request-header modifications.
 *
 * - All arguments are single-quoted to prevent bash injection.
 * - Only enabled request-header rules whose operation is `set` or `append`
 *   contribute `-H` flags.
 * - Response-header rules are intentionally ignored because `curl` cannot
 *   reproduce server-side response header mutations.
 * - The command uses line-continuations for readability.
 */
export function exportToCurl(
  url: string,
  cookies: chrome.cookies.Cookie[],
  headers: HeaderRule[],
): string {
  const parts: string[] = [`curl '${shEscape(url)}'`];

  if (cookies.length > 0) {
    const cookieStr = cookies.map(c => `${c.name}=${c.value}`).join('; ');
    parts.push(`  -b '${shEscape(cookieStr)}'`);
  }

  for (const rule of headers) {
    if (!rule.enabled) continue;
    const mods = rule.requestHeaders ?? [];
    for (const mod of mods) {
      if (mod.operation !== 'remove' && mod.value !== undefined) {
        parts.push(`  -H '${shEscape(mod.header)}: ${shEscape(mod.value)}'`);
      }
    }
  }

  return parts.join(' \\\n');
}

/**
 * Formats cookies as a Netscape HTTP Cookie File.
 *
 * The tab-separated fields in each record are (in order):
 *   domain  include_subdomains  path  https_only  expiry_unix  name  value
 *
 * This format is consumed by curl (`--cookie <file>`), yt-dlp, wget, and
 * other CLI tools.  Tab characters inside field values are replaced with
 * spaces to keep every record on a single line.
 *
 * Session cookies (no expirationDate) get an expiry of 0, which most tools
 * interpret as "valid for the current session".
 */
export function exportToNetscape(cookies: chrome.cookies.Cookie[]): string {
  const lines: string[] = [
    '# Netscape HTTP Cookie File',
    '# Generated by OWASP Web Security Inspector',
    '',
  ];

  for (const c of cookies) {
    const subdomains = c.domain.startsWith('.') ? 'TRUE' : 'FALSE';
    const httpsOnly  = c.secure ? 'TRUE' : 'FALSE';
    const expires    = c.expirationDate != null ? String(Math.floor(c.expirationDate)) : '0';
    const path  = (c.path  || '/').replace(/\t/g, ' ');
    const name  = c.name.replace(/\t/g, ' ');
    const value = c.value.replace(/\t/g, ' ');
    lines.push(`${c.domain}\t${subdomains}\t${path}\t${httpsOnly}\t${expires}\t${name}\t${value}`);
  }

  return lines.join('\n');
}
